spring:
  data:
    cassandra:
      keyspace-name: main
      username: NBjivLTUomLnZbKoUpZLdLEZ
      password: T-b6XzlzZA0t5nI0LLbG6ExpjgJPICzPol0_g+jsyrFplsfQ78f8l+9_lfPfta2l.rhie1IZNGXlemlD_AO,bxgfkqIjJrg0WZFWFpZDSDRbFQdpthLUNjbhs1+Jm,8F
      schema-action: create_if_not_exists
      request:
        timeout: 10s
      connection:
        connect-timeout: 10s
        init-query-timeout: 10s

datastax.astra:
    secure-connect-bundle: secure-connect.zip

astra.db
    id: 6846e70e-b94f-46ce-9c28-092c05b83a2c-1
    region: asia-south1
    keyspace: main
    application.token: AstraCS:NBjivLTUomLnZbKoUpZLdLEZ:4f62110fab98c57bd0b42ef449ea81a9298891a5e1a8f8925608e0797d4468e0
